apiVersion: apps/v1
kind: Deployment
metadata:
  name: optitlab-react-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optitlab-react-dev
  template:
    metadata:
      labels:
        app: optitlab-react-dev
    spec:
      containers:
      - name: optitlab-react-container
        image: bharathoptdocker/reactjs:latest 
        ports:
          - containerPort: 80
