apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopshelm02
  name: optitlab-reactjs-dev
  labels:
    app: optitlab-reactjs-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: optitlab-reactjs-dev
  template:
    metadata:
      labels:
        app: optitlab-reactjs-dev
    spec:
      containers:
      - name: optitlab-reactjs-dev
        image: bharathoptdocker/reactjs:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
