apiVersion: apps/v1
kind: Deployment
metadata:
  name: optit-lab-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optit-lab-react
  template:
    metadata:
      labels:
        app: optit-lab-react
    spec:
      containers:
      - name: optit-lab-react-container
        image: bharathoptdocker/reactjs:latest 
        ports:
        - containerPort: 80
