apiVersion: v1
kind: Service
metadata:
  namespace: devopshelm02
  name: optitlab-reactjs-dev
  labels:
    app: optitlab-reactjs-dev
spec:
  selector:
    app: optitlab-reactjs-dev
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 80
